export const leaderboardData = [
  {
    Rank: 1,
    Name: "Selling with re entry",
    "Calmar Ratio": 3.96,
    "Overall Profit": 381845,
    "Daily Profit": 319.54,
    "Win %Day": 0.65,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 2,
    Name: "strategy_name",
    "Calmar Ratio": 3.62,
    "Overall Profit": 268872.5,
    "Daily Profit": 216.31,
    "Win %Day": 0.64,
    "Price (Rs)": 500,
    Action: "Buy",
  },
  {
    Rank: 3,
    Name: "Based on premium and",
    "Calmar Ratio": 3.42,
    "Overall Profit": 255425,
    "Daily Profit": 208.51,
    "Win %Day": 0.64,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 4,
    Name: "strategy_name",
    "Calmar Ratio": 3.22,
    "Overall Profit": 370845,
    "Daily Profit": 303.47,
    "Win %Day": 0.65,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 5,
    Name: "strategy_name",
    "Calmar Ratio": 3.22,
    "Overall Profit": 370845,
    "Daily Profit": 303.47,
    "Win %Day": 0.65,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 6,
    Name: "Based on premium wit",
    "Calmar Ratio": 3.01,
    "Overall Profit": 135980,
    "Daily Profit": 185.77,
    "Win %Day": 0.49,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 7,
    Name: "strategy_name",
    "Calmar Ratio": 2.76,
    "Overall Profit": 267867.5,
    "Daily Profit": 218.49,
    "Win %Day": 0.6,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 8,
    Name: "Wait and trade_Save",
    "Calmar Ratio": 2.62,
    "Overall Profit": 178252.5,
    "Daily Profit": 161.9,
    "Win %Day": 0.63,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 9,
    Name: "iron condor",
    "Calmar Ratio": 2.44,
    "Overall Profit": 176420,
    "Daily Profit": 137.51,
    "Win %Day": 0.65,
    "Price (Rs)": "-",
    Action: "View",
  },
  {
    Rank: 10,
    Name: "strategy_name",
    "Calmar Ratio": 2.04,
    "Overall Profit": 244555,
    "Daily Profit": 198.66,
    "Win %Day": 0.62,
    "Price (Rs)": "-",
    Action: "View",
  },
];


export const searchRes = [
  "Bollinger Bands (BBANDS upperband)",
  "Bollinger Bands (BBANDS middleband)",
  "Bollinger Bands (BBANDS lowerband)",
  "Exponential Moving Average (EMA)",
  "Parabolic SAR (SAR)",
  "Simple Moving Average (SMA)",
  "Weighted Moving Average (WMA)",
  "Average Directional Movement Index (ADX)",
  "Average Directional Movement Index Rating (ADXR)",
  "Aroon-Up (AROON-UP)",
  "Aroon_Down (AROON-DOWN)",
  "Aroon Oscillator (AROONOSC)",
  "Balance Of Power (BOP)",
  "Commodity Channel Index (CCI)",
  "Moving Average Convergence/Divergence (MACD)",
  "Money Flow Index (MFI)",
  "Volume Weighted Average Price (VWAP)",
  "Rate of change : ((price/prevPrice)-1)*100 (ROC)",
  "Relative Strength Index (RSI)",
  "1-day Rate-Of-Change (ROC) of a Triple Smooth EMA (TRIX)",
  "Williams' %R (WILLR)",
  "On Balance Volume (OBV)",
  "Average True Range (ATR)",
  "Average Price (AVGPRICE)",
  "Two Crows (CDL2CROWS)",
  "Three Black Crows (CDL3BLACKCROWS)",
  "Three-Line Strike (CDL3LINESTRIKE)",
  "Three Outside Up/Down (CDL3OUTSIDE)",
  "Three Stars In The South (CDL3STARSINSOUTH)",
  "Three Advancing White Soldiers (CDL3WHITESOLDIERS)",
  "Advance Block (CDLADVANCEBLOCK)",
  "Belt-hold (CDLBELTHOLD)",
  "Breakaway (CDLBREAKAWAY)",
  "Closing Marubozu (CDLCLOSINGMARUBOZU)",
  "Concealing Baby Swallow (CDLCONCEALBABYSWALL)",
  "Doji (CDLDOJI)",
  "Doji Star (CDLDOJISTAR)",
  "Dragonfly Doji (CDLDRAGONFLYDOJI)",
  "Engulfing Pattern (CDLENGULFING)",
  "Gravestone Doji (CDLGRAVESTONEDOJI)",
  "Hammer (CDLHAMMER)",
  "Hanging Man (CDLHANGINGMAN)",
  "Harami Pattern (CDLHARAMI)",
  "Harami Cross Pattern (CDLHARAMICROSS)",
  "High-Wave Candle (CDLHIGHWAVE)",
  "Hikkake Pattern (CDLHIKKAKE)",
  "Modified Hikkake Pattern (CDLHIKKAKEMOD)",
  "Homing Pigeon (CDLHOMINGPIGEON)",
  "Identical Three Crows (CDLIDENTICAL3CROWS)",
  "In-Neck Pattern (CDLINNECK)",
  "Inverted Hammer (CDLINVERTEDHAMMER)",
  "Kicking (CDLKICKING)",
  "Kicking - bull/bear determined by the longer marubozu (CDLKICKINGBYLENGTH)",
  "Ladder Bottom (CDLLADDERBOTTOM)",
  "Long Legged Doji (CDLLONGLEGGEDDOJI)",
  "Long Line Candle (CDLLONGLINE)",
  "Marubozu (CDLMARUBOZU)",
  "Matching Low (CDLMATCHINGLOW)"
]
